export const ENDPOINTS = {
  AUTH: {
    LOGIN: "/auth/login",
    LOGOUT: "/auth/logout",
    ME: "/auth/me",
  },
  USERS: {
    LIST: "/users",
    DETAIL: (id: number) => `/users/${id}`,
    PROFILE: "/users/profile",
    UPDATE: (id: number) => `/users/${id}`,
    DELETE: (id: number) => `/users/${id}`,
    IMPORT: "/users/import",
    EXPORT: "/users/export",
  },
  CLASSES: {
    LIST: "/classes",
    DETAIL: (id: number) => `/classes/${id}`,
    UPDATE: (id: number) => `/classes/${id}`,
    DELETE: (id: number) => `/classes/${id}`,
    MEMBERS: (id: number) => `/classes/${id}/members`,
    ENROLL: (id: number) => `/classes/${id}/enroll`,
  },
  COURSES: {
    LIST: "/courses",
    CREATE: "/courses",
    DETAIL: (id: number) => `/courses/${id}`,
    UPDATE: (id: number) => `/courses/${id}`,
    DELETE: (id: number) => `/courses/${id}`,
    CHAPTERS: (id: number) => `/courses/${id}/chapters`,
    MATERIALS: (id: number) => `/courses/${id}/materials`,
    UPLOAD: (id: number) => `/courses/${id}/materials/upload`,
    DOWNLOAD_MATERIAL: (courseId: number, materialId: number) => `/courses/${courseId}/materials/${materialId}/download`,
  },
  CHAPTERS: {
    DETAIL: (id: number) => `/chapters/${id}`,
    MATERIALS: (id: number) => `/chapters/${id}/materials`,
  },
  ASSIGNMENTS: {
    LIST: "/assignments",
    DETAIL: (id: number) => `/assignments/${id}`,
    CREATE: "/assignments",
    UPDATE: (id: number) => `/assignments/${id}`,
    DELETE: (id: number) => `/assignments/${id}`,
  },
  ASSIGNMENT_ATTACHMENTS: {
    CREATE: "/assignment-attachments",
    DETAIL: (id: number) => `/assignment-attachments/${id}`,
    BY_ASSIGNMENT: (assignmentId: number) => `/assignment-attachments/assignment/${assignmentId}`,
    DELETE: (id: number) => `/assignment-attachments/${id}`,
  },
  SUBMISSIONS: {
    CREATE: "/submissions",
    UPLOAD: "/submissions/upload",
    DETAIL: (id: number) => `/submissions/${id}`,
    BY_ASSIGNMENT: (assignmentId: number) => `/submissions/assignment/${assignmentId}`,
    GRADE: (id: number) => `/submissions/${id}/grade`,
    DELETE: (id: number) => `/submissions/${id}`,
  },
  EXAMS: {
    LIST: "/exams",
    DETAIL: (id: number) => `/exams/${id}`,
    CREATE: "/exams",
    UPDATE: (id: number) => `/exams/${id}`,
    DELETE: (id: number) => `/exams/${id}`,
    QUESTIONS: (id: number) => `/exams/${id}/questions`,
    TAKE: (id: number) => `/exams/${id}/take`,
    SUBMIT: (id: number) => `/exams/${id}/submit`,
    RESULT: (id: number) => `/exams/${id}/result`,
    SUBMISSIONS: (id: number) => `/exams/${id}/submissions`,
    GRADE: (id: number) => `/exams/${id}/grade`,
    DOWNLOAD_ATTACHMENT: (examId: number, attachmentId: number) => `/exams/${examId}/attachments/${attachmentId}/download`,
    DOWNLOAD_SUBMISSION: (examId: number, submissionId: number) => `/exams/${examId}/submissions/${submissionId}/download`,
  },
  GRADES: {
    LIST: "/grades",
    MY_GRADES: "/grades/me",
    COURSE_GRADES: (courseId: number) => `/grades/course/${courseId}`,
    CLASS_GRADES: (classId: number) => `/grades/class/${classId}`,
    EXPORT: "/grades/export",
  },
  DISCUSSIONS: {
    LIST: "/discussions",
    DETAIL: (id: number) => `/discussions/${id}`,
    CREATE: "/discussions",
    UPDATE: (id: number) => `/discussions/${id}`,
    DELETE: (id: number) => `/discussions/${id}`,
    REPLIES: (id: number) => `/discussions/${id}/replies`,
    LIKE: (id: number) => `/discussions/${id}/like`,
  },
  SCHEDULE: {
    LIST: "/schedule",
    CREATE: "/schedule",
    UPDATE: (id: number) => `/schedule/${id}`,
    DELETE: (id: number) => `/schedule/${id}`,
  },
  REPORTS: {
    STATS: "/reports/stats",
    ENROLLMENT: "/reports/enrollment",
    SUBMISSIONS: "/reports/submissions",
    TOP_STUDENTS: "/reports/top-students",
  },
} as const;
